// <auto-generated />
namespace ReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class KontenjanEkle10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KontenjanEkle10));
        
        string IMigrationMetadata.Id
        {
            get { return "202512301226299_KontenjanEkle10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
